### ISSUE TITLE
Fix asimba.xml CE template

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAsimba#1]
This asimba.xml is te part of CE setup: https://github.com/GluuFederation/community-edition-setup/blob/master/templates/asimba.xml

We need to fix is to provides default minimal configuration. If it possible we need to configure it to use local LDAP for user authentication.

**Comment by nynymike** [comment]
I would say by default it should point at the Gluu Server Shibboleth IDP.

**Comment by yurem** [comment]
Should we introduce components dependency in setup for this case? If user select asimba should we select IDP?

**Comment by yurem** [comment]
We uses gluu-Asimba now
