### ISSUE TITLE
Automate Asimba configuration in CE

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAsimba#2]
Here is how we configured Asimba 1.3.0 manually in Gluu CE 2.x.x 
http://ox.gluu.org/doku.php?id=ce:asimba130reconfiguration

Let's make a velocity template for asimba.xml.

**Comment by nynymike** [comment]
It would be great if we could manage IDPs and SPs for Asimba. I wonder if we should just render XML like we do with the Shibboleth IDP. Another option would be to perhaps write an LDAP interface for asimba. There is already a MySQL implementation that could serve as a guide.

**Comment by yurem** [comment]
We uses gluu-Asimba now
