### ISSUE TITLE
'Trust Certificate File' option in 'IDP' of 'SP' is not working properly

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAsimba#3]
Remote IDP/ADFS or SP SAML cert should be inserted 'asimbaIDP.jks' with this oxTrust feature, but it's not working. Still we need to manually import SAML cert for  IDP/ADFS or SP into 'asimbaIDP.jks' with keytool command.

**Comment by dmogn** [comment]
Yeh, I found the problem. oxTrust's SSLService certificate reader accept .pem, not .crt.
I should use more universal reader.

**Comment by dmogn** [comment]
Fixed. @mzico - check, please.

**Comment by mzico** [comment]
@dmogn : Thanks! Which artifact should I pull to test? oxAsimba or oxTrust?

**Comment by dmogn** [comment]
1. Add a certificate to SP/IDP in oxTrust.
2. Check it in "SAML->Certificates" page. It's easist way to look to keystore.

**Comment by dmogn** [comment]
Hm... I found the bug. ID should be filled before cert upload. Or cert will be saved with wrong alias. I'll fix it in monday.

**Comment by dmogn** [comment]
![certificate monitoring](https://cloud.githubusercontent.com/assets/14166017/15835202/4127ded6-2c05-11e6-9ca4-b0f1c7ab95cb.jpg)

**Comment by mzico** [comment]
@dmogn : Do you want me to test? If yes.. same question again... :-) 

>> Which artifact should I pull to test? oxAsimba or oxTrust?

**Comment by dmogn** [comment]
It's oxTrust only change (in UI).

**Comment by dmogn** [comment]
Ok. Tested.
