### ISSUE TITLE
Uploading metadata for remote SP/IDP not working

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAsimba#5]
If deployer prefer to use 'upload' option than using static path or metadata URL, then there is actually no option to do that. "Upload" metadata option for IDP or SP is not working.

**Comment by dmogn** [comment]
Fixed. @mzico - check, please.

**Comment by mzico** [comment]
@dmogn : I'll test and inform you the status.

**Comment by dmogn** [comment]
"Certiiificates" page do not shows the certificate too?

**Comment by dmogn** [comment]
root@ce:/opt/gluu-server-2.4.3/etc/certs# keytool -list -v -keystore asimbaIDP.jks
Enter keystore password:  

Keystore type: JKS
Keystore provider: SUN

Your keystore contains 7 entries
...
*******************************************


Alias name: https://test.gluu.info/idp/shibboleth3
Creation date: Jun 6, 2016
Entry type: trustedCertEntry

Owner: CN=ce.test.gluu.info
Issuer: CN=ce.test.gluu.info
Serial number: c709546f3fe6682b
Valid from: Mon Jun 06 13:13:35 UYT 2016 until: Tue Jun 07 13:13:35 UYT 2016
Certificate fingerprints:
         MD5:  D9:AA:66:34:3E:6A:62:65:EF:65:94:DA:CE:DF:1B:06
         SHA1: FE:13:65:17:0A:97:F8:FF:AF:D9:7B:EC:04:86:AD:F8:56:66:07:F7
         SHA256: 59:82:E5:B7:C4:85:4F:10:38:AA:8E:EB:24:1B:24:4D:29:77:F5:B1:52:8D:B3:E4:71:30:77:36:3A:FB:9D:80
         Signature algorithm name: SHA256withRSA
         Version: 3
.....

**Comment by dmogn** [comment]
Yeh, I found the problem.

Fixed. @mzico - check, please.

**Comment by mzico** [comment]
@dmogn : Huge improvement!! Now oxTrust can grab the cert and metadata and insert them properly. However, I still need to restart tomcat to grab the changes. 

oxTrust version: 

```
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 2.4.4-SNAPSHOT
Implementation-Vendor-Id: org.xdi
Built-By: tomcat
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
Implementation-Build: 45de1
Archiver-Version: Plexus Archiver
```

**Comment by dmogn** [comment]
Nice! I close this issue.

**Comment by mzico** [comment]
@dmogn : We still need to restart tomcat to apply changes....

**Comment by dmogn** [comment]
@mzico  We have separate issue for this: https://github.com/GluuFederation/oxAsimba/issues/4

It's new functionality, I cannot add it in 2.4.4.

**Comment by mzico** [comment]
ah..ok... thanks!
